import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Footer} from "@/app/components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'kametsun',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + "flex flex-col items-center justify-center"}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
